
package interfaces;
import controle.ControladorCadastroClientes;
import controle.ControladorCadastroImóveis;
import persistencia.BD;

public class JanelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal() {
        BD.criaConexao();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        clienteMenu = new javax.swing.JMenu();
        cadastroClienteMenuItem = new javax.swing.JMenuItem();
        imoveisMenu = new javax.swing.JMenu();
        cadastroImoveisMenuItem = new javax.swing.JMenuItem();
        negocioMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Imobiliária");

        clienteMenu.setText("Cliente");

        cadastroClienteMenuItem.setText("Cadastro");
        cadastroClienteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroClientes(evt);
            }
        });
        clienteMenu.add(cadastroClienteMenuItem);

        jMenuBar1.add(clienteMenu);

        imoveisMenu.setText("Imóveis");

        cadastroImoveisMenuItem.setText("Cadastro");
        cadastroImoveisMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroImoveis(evt);
            }
        });
        imoveisMenu.add(cadastroImoveisMenuItem);

        jMenuBar1.add(imoveisMenu);

        negocioMenu.setText("Negócio");
        jMenuBar1.add(negocioMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastroClientes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroClientes
        new ControladorCadastroClientes();
    }//GEN-LAST:event_cadastroClientes

    private void cadastroImoveis(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroImoveis
        new ControladorCadastroImóveis();
    }//GEN-LAST:event_cadastroImoveis

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cadastroClienteMenuItem;
    private javax.swing.JMenuItem cadastroImoveisMenuItem;
    private javax.swing.JMenu clienteMenu;
    private javax.swing.JMenu imoveisMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu negocioMenu;
    // End of variables declaration//GEN-END:variables
}
