
package interfaces;

import controle.ControladorCadastroClientes;
import entidade.Cliente;
import entidade.Visão;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

public class JanelaCadastroClientes extends javax.swing.JFrame {

    ControladorCadastroClientes controlador; //fará a intermediacao com o controlador e a janela
    Vector <Visão <String>> visaoClientesCadastrados;
    
    
    /**
     * Creates new form JanelaCadastroClientes
     */
    public JanelaCadastroClientes(ControladorCadastroClientes controlador) {
        this.controlador = controlador;
        visaoClientesCadastrados = Cliente.getVisões(); //o comboBox esta com o model associado a esse vetor, pega visao dos clientes cadastrados no BD
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clientesCadastradosLabel = new javax.swing.JLabel();
        nomeLabel = new javax.swing.JLabel();
        cpfLabel = new javax.swing.JLabel();
        rendaLabel = new javax.swing.JLabel();
        telefoneLabel = new javax.swing.JLabel();
        profissaoLabel = new javax.swing.JLabel();
        nomeTextField = new javax.swing.JTextField();
        cpfTextField = new javax.swing.JTextField();
        rendaTextField = new javax.swing.JTextField();
        telefoneTextField = new javax.swing.JTextField();
        profissaoTextField = new javax.swing.JTextField();
        clientesCadastradosComboBox = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        inserirButton = new javax.swing.JButton();
        alterarButton = new javax.swing.JButton();
        removerButton = new javax.swing.JButton();
        consultarButton = new javax.swing.JButton();
        limparButton = new javax.swing.JButton();

        setTitle("Cadastro de Clientes");

        clientesCadastradosLabel.setText("Clientes Cadastrados:");

        nomeLabel.setText("Nome:");

        cpfLabel.setText("CPF:");

        rendaLabel.setText("Renda Bruta:");

        telefoneLabel.setText("Telefone:");

        profissaoLabel.setText("Profissão:");

        nomeTextField.setColumns(50);

        cpfTextField.setColumns(11);

        rendaTextField.setColumns(6);

        telefoneTextField.setColumns(15);

        profissaoTextField.setColumns(20);

        clientesCadastradosComboBox.setModel(new DefaultComboBoxModel(visaoClientesCadastrados));

        inserirButton.setText("Inserir");
        inserirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirCliente(evt);
            }
        });

        alterarButton.setText("Alterar");
        alterarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarCliente(evt);
            }
        });

        removerButton.setText("Remover");
        removerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerCliente(evt);
            }
        });

        consultarButton.setText("Consultar");
        consultarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarCliente(evt);
            }
        });

        limparButton.setText("Limpar");
        limparButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparCampos(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inserirButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alterarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removerButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(consultarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(limparButton)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inserirButton)
                    .addComponent(alterarButton)
                    .addComponent(removerButton)
                    .addComponent(consultarButton)
                    .addComponent(limparButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(telefoneLabel)
                                    .addComponent(rendaLabel)
                                    .addComponent(profissaoLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rendaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(telefoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(profissaoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(clientesCadastradosLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(clientesCadastradosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(cpfLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cpfTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientesCadastradosLabel)
                    .addComponent(clientesCadastradosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeLabel)
                    .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfLabel)
                    .addComponent(cpfTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rendaLabel)
                    .addComponent(rendaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefoneLabel)
                    .addComponent(telefoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profissaoLabel)
                    .addComponent(profissaoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inserirCliente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirCliente
        // TODO add your handling code here:
        Cliente novo = obtemDados();
        String mensagem_erro = null;
        
        if(novo != null) //todos os campos preenchidos
           mensagem_erro = controlador.inserirCliente(novo); //se der certo retorna null
        else
            mensagem_erro = "Algum campo não foi preenchido :(";
        
        if(mensagem_erro == null){ //se foi inserido
            Visão <String> visao = novo.getVisao(); //extrai visao na entidade
            clientesCadastradosComboBox.addItem(visao); //adiciona visao no comboBox
            clientesCadastradosComboBox.setSelectedItem(visao); //seta o ultimo cliente adicionado
        }
         else
            JOptionPane.showMessageDialog(this, mensagem_erro, "OPS!", JOptionPane.ERROR_MESSAGE);
        
    }//GEN-LAST:event_inserirCliente

    private void alterarCliente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarCliente
        // TODO add your handling code here:
        Cliente cliente = obtemDados();
        String mensagem_erro = null;

        if(cliente != null){
            mensagem_erro = controlador.alterarCliente(cliente);
        }
         else{
            mensagem_erro = "Algum campo não foi preenchido :(";
         }

         if(mensagem_erro == null){
            Visão <String> visaoAntiga = getVisãoAntiga(cliente.getCpf()); //pega visao antiga do comboBox na forma: [nome - cpf]

            if(visaoAntiga != null){
                visaoAntiga.setDados(cliente.getVisao().getDados()); //altera os dados da visao antiga
                clientesCadastradosComboBox.updateUI(); //atualiza visao antiga no comboBox
                clientesCadastradosComboBox.setSelectedItem(visaoAntiga); //seta visao atual 
            }
             
         }
          else
             JOptionPane.showMessageDialog(this, mensagem_erro, "OPS!", JOptionPane.ERROR_MESSAGE);

    }//GEN-LAST:event_alterarCliente

    private void removerCliente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerCliente
        // TODO add your handling code here:
        Visão <String> visao = (Visão <String>) clientesCadastradosComboBox.getSelectedItem();// converte o objeto do comboBox para objeto Visao <String>
        String mensagem_erro;

        if(visao != null)
            mensagem_erro = controlador.removerCliente(visao.getChave());
         else
            mensagem_erro = "Nenhum Cliente Selecionado";

        if(mensagem_erro == null){
            visaoClientesCadastrados.remove(visao);
            
            if(visaoClientesCadastrados.size() > 0)
                clientesCadastradosComboBox.setSelectedIndex(0);
            else
                clientesCadastradosComboBox.setSelectedIndex(-1); //seleciona vazio
        }
         else
            JOptionPane.showMessageDialog(this, mensagem_erro, "OPS!",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_removerCliente

    private void consultarCliente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarCliente
        // TODO add your handling code here:
        Visão<String> visaoSelecionada = (Visão<String>)clientesCadastradosComboBox.getSelectedItem();
        Cliente cliente = null;
        String mensagem_erro = null;

        if(visaoSelecionada != null)
            cliente = Cliente.buscarCliente(visaoSelecionada.getChave());
         else
            mensagem_erro = "Nenhum Cliente Selecionado";

        if(mensagem_erro == null){

            nomeTextField.setText(cliente.getNome());
            cpfTextField.setText(cliente.getCpf());
            rendaTextField.setText(Float.toString(cliente.getRendaBruta()));
            telefoneTextField.setText(cliente.getTelefone());
            profissaoTextField.setText(cliente.getProfissao());
        }
         else
            JOptionPane.showMessageDialog(this, mensagem_erro, "OPS!", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_consultarCliente

    private void limparCampos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparCampos
        // TODO add your handling code here:
        nomeTextField.setText("");
        cpfTextField.setText("");
        rendaTextField.setText("");
        telefoneTextField.setText("");
        profissaoTextField.setText("");

    }//GEN-LAST:event_limparCampos

    //lê os dados do campo de texto verificando se nao sao nulos
    private Cliente obtemDados(){
        
        String nome = nomeTextField.getText();
        if(nome.equals(""))
            return null;
        
        String cpf = cpfTextField.getText();
        if(cpf.equals(""))
            return null;
        
       String renda = rendaTextField.getText();
        if(renda.equals(""))
            return null;
        
        String tel = telefoneTextField.getText();
        if(tel.equals(""))
            return null;
        
        String profissao = profissaoTextField.getText();
        if(profissao.equals(""))
            return null;
        
        //converte String para float;
        return new Cliente (nome, cpf, Float.parseFloat(renda), tel, profissao);
    } 

    private Visão <String> getVisãoAntiga(String cpf){
        for(Visão<String> visao : visaoClientesCadastrados)
            if(visao.getChave().equals(cpf))
                return visao;

        return null;
    }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterarButton;
    private javax.swing.JComboBox clientesCadastradosComboBox;
    private javax.swing.JLabel clientesCadastradosLabel;
    private javax.swing.JButton consultarButton;
    private javax.swing.JLabel cpfLabel;
    private javax.swing.JTextField cpfTextField;
    private javax.swing.JButton inserirButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton limparButton;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JTextField nomeTextField;
    private javax.swing.JLabel profissaoLabel;
    private javax.swing.JTextField profissaoTextField;
    private javax.swing.JButton removerButton;
    private javax.swing.JLabel rendaLabel;
    private javax.swing.JTextField rendaTextField;
    private javax.swing.JLabel telefoneLabel;
    private javax.swing.JTextField telefoneTextField;
    // End of variables declaration//GEN-END:variables
}
