
package interfaces;

import controle.ControladorCadastroImóveis;
import entidade.Cômodos;
import entidade.Endereço;
import static entidade.Endereço.ESTADO;
import entidade.Endereço.Estado;
import entidade.Imóvel;
import entidade.Imóvel.Tipo;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;


public class JanelaCadastroImóveis extends javax.swing.JFrame {
    
    ControladorCadastroImóveis controlador;
    Estado[] listaEstados;
    
    /**
     * Creates new form JanelaCadastroImóveis
     */
    public JanelaCadastroImóveis(ControladorCadastroImóveis controlador) {
        this.controlador = controlador;
        listaEstados = ESTADO; //o model do comboBox esta associado a essa variavel
        initComponents();
        estadoComboBox.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBotoesbuttonGroup = new javax.swing.ButtonGroup();
        ruaLabel = new javax.swing.JLabel();
        numeroLabel = new javax.swing.JLabel();
        complementoLabel = new javax.swing.JLabel();
        bairroLabel = new javax.swing.JLabel();
        estadoLabel = new javax.swing.JLabel();
        cidadeLabel = new javax.swing.JLabel();
        dormitoriosLabel = new javax.swing.JLabel();
        ambientesLabel = new javax.swing.JLabel();
        servicosLabel = new javax.swing.JLabel();
        bwcLabel = new javax.swing.JLabel();
        areaToataLabel = new javax.swing.JLabel();
        valorLabel = new javax.swing.JLabel();
        casaRadioButton = new javax.swing.JRadioButton();
        apartamentoRadioButton = new javax.swing.JRadioButton();
        enderecoLabel = new javax.swing.JLabel();
        comodosLabel = new javax.swing.JLabel();
        estadoComboBox = new javax.swing.JComboBox();
        ruaTextField = new javax.swing.JTextField();
        numeroTextField = new javax.swing.JTextField();
        complementoTextField = new javax.swing.JTextField();
        bairroTextField = new javax.swing.JTextField();
        cidadeTextField = new javax.swing.JTextField();
        dormitoriosTextField = new javax.swing.JTextField();
        ambientesTextField = new javax.swing.JTextField();
        servicosTextField = new javax.swing.JTextField();
        bwcTextField = new javax.swing.JTextField();
        areaTextField = new javax.swing.JTextField();
        valorTextField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        inserirButton = new javax.swing.JButton();
        alterarButton = new javax.swing.JButton();
        removerButton = new javax.swing.JButton();
        consultarButton = new javax.swing.JButton();
        limparButton = new javax.swing.JButton();
        segurancaCheckBox = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        sequencialLabel = new javax.swing.JLabel();
        sequencialTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cepLabel = new javax.swing.JLabel();
        cepTextField = new javax.swing.JTextField();

        setTitle("Cadastro de Imóveis");

        ruaLabel.setText("Rua:");

        numeroLabel.setText("Numero:");

        complementoLabel.setText("Complemento:");

        bairroLabel.setText("Bairro:");

        estadoLabel.setText("Estado:");

        cidadeLabel.setText("Cidade:");

        dormitoriosLabel.setText("Dormitórios:");

        ambientesLabel.setText("Ambientes:");

        servicosLabel.setText("Serviços:");

        bwcLabel.setText("BWC:");

        areaToataLabel.setText("Área Total:");

        valorLabel.setText("Valor:");

        grupoBotoesbuttonGroup.add(casaRadioButton);
        casaRadioButton.setText("Casa");

        grupoBotoesbuttonGroup.add(apartamentoRadioButton);
        apartamentoRadioButton.setText("Apartamento");

        enderecoLabel.setText("ENDEREÇO:");

        comodosLabel.setText("COMODOS:");

        estadoComboBox.setModel(new DefaultComboBoxModel(listaEstados));

        inserirButton.setText("Inserir");
        inserirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirImovel(evt);
            }
        });

        alterarButton.setText("Alterar");
        alterarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarImovel(evt);
            }
        });

        removerButton.setText("Remover");
        removerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerImovel(evt);
            }
        });

        consultarButton.setText("Consultar");
        consultarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarImovel(evt);
            }
        });

        limparButton.setText("Limpar");
        limparButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparCampos(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(inserirButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alterarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removerButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(consultarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(limparButton)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inserirButton)
                    .addComponent(alterarButton)
                    .addComponent(removerButton)
                    .addComponent(consultarButton)
                    .addComponent(limparButton))
                .addGap(14, 14, 14))
        );

        segurancaCheckBox.setText("Segurança 24hrs");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        sequencialLabel.setText("Sequencial:");

        sequencialTextField.setEditable(false);

        jLabel1.setText("Imóveis Cadastrados:");

        jLabel2.setText("m²");

        cepLabel.setText("CEP:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sequencialTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sequencialLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(enderecoLabel)))
                .addContainerGap(89, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(complementoLabel)
                                    .addComponent(bairroLabel)
                                    .addComponent(estadoLabel)
                                    .addComponent(cidadeLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(complementoTextField)
                                    .addComponent(cidadeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(estadoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bairroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(areaToataLabel)
                                    .addComponent(valorLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(valorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(areaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2)))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(apartamentoRadioButton)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(casaRadioButton)
                                        .addGap(62, 62, 62)
                                        .addComponent(segurancaCheckBox))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(numeroLabel)
                                    .addComponent(ruaLabel)
                                    .addComponent(cepLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numeroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ruaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cepTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(236, 236, 236)
                                .addComponent(comodosLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bwcLabel)
                                    .addComponent(dormitoriosLabel)
                                    .addComponent(servicosLabel)
                                    .addComponent(ambientesLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ambientesTextField)
                                    .addComponent(servicosTextField)
                                    .addComponent(dormitoriosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bwcTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sequencialLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sequencialTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(15, 15, 15)
                .addComponent(enderecoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cepLabel)
                    .addComponent(cepTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ruaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ruaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numeroLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(complementoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(complementoLabel))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(estadoLabel)
                            .addComponent(estadoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bairroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bairroLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cidadeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cidadeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comodosLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dormitoriosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dormitoriosLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ambientesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ambientesLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(servicosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(servicosLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bwcLabel)
                    .addComponent(bwcTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(casaRadioButton)
                            .addComponent(segurancaCheckBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(apartamentoRadioButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(areaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(areaToataLabel)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(valorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(valorLabel))))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inserirImovel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirImovel
        // TODO add your handling code here:
        Imóvel imovel = obtemDados();
        String mensagem_erro = null;
        
        if(imovel != null)
            mensagem_erro = controlador.inserirImovel(imovel);
        else
            mensagem_erro = "Algum Campo Obrigatório Não Foi Preenchido!!";
        
            if(mensagem_erro == null){
                //insere em um List ou TextArea
            }
             else
                JOptionPane.showMessageDialog(this, mensagem_erro, "OPS!", JOptionPane.ERROR_MESSAGE);
                   
    }//GEN-LAST:event_inserirImovel

    private void alterarImovel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarImovel
        // TODO add your handling code here:
        Imóvel imovel = obtemDados();
        String mensagem_erro = null;
        
        if(imovel != null)
            mensagem_erro = controlador.alterarImovel(imovel);
        else
            mensagem_erro = "Algum Campo Obrigatório Não Foi Preenchido!!";
        
            if(mensagem_erro == null){
                //Obtem visao e altera no List
            }
             else
                 JOptionPane.showMessageDialog(this, mensagem_erro, "OPS!", JOptionPane.ERROR_MESSAGE);               
    }//GEN-LAST:event_alterarImovel

    private void removerImovel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerImovel
        // TODO add your handling code here:
        
    }//GEN-LAST:event_removerImovel

    private void consultarImovel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarImovel
        // TODO add your handling code here:
    }//GEN-LAST:event_consultarImovel

    private void limparCampos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparCampos
        // TODO add your handling code here:
        cepTextField.setText("");
        ruaTextField.setText("");
        numeroTextField.setText("");
        complementoTextField.setText("");
        bairroTextField.setText("");
        estadoComboBox.setSelectedIndex(-1);
        cidadeTextField.setText("");

        dormitoriosTextField.setText("");
        ambientesTextField.setText("");
        servicosTextField.setText("");
        bwcTextField.setText("");

        areaTextField.setText("");
        valorTextField.setText("");
        segurancaCheckBox.setSelected(false);
        grupoBotoesbuttonGroup.clearSelection();      
    }//GEN-LAST:event_limparCampos

    private Imóvel obtemDados(){
        
        String cep = cepTextField.getText();
        if(cep.equals(""))
            return null;
       
        String rua = ruaTextField.getText();
        if(rua.equals(""))
            return null;
        
        String num = numeroTextField.getText();
        if(num.equals(""))
            return null;
                
        String complemento = complementoTextField.getText();
        
        String bairro = bairroTextField.getText();
        if(bairro.equals(""))
            return null;
        
        Estado estado = null;
        if(estadoComboBox.getSelectedItem() != null) //se NAO tiver indice -1 selecionado (nada)
             estado = (Endereço.Estado)estadoComboBox.getSelectedItem();
        else
            return null;
        
        String cidade = cidadeTextField.getText();
        if(cidade.equals(""))
            return null;
        
        Endereço endereco = new Endereço(cep, rua, Integer.parseInt(num), complemento, bairro, estado, cidade);
        
        String dormitorios = dormitoriosTextField.getText();
        if(dormitorios.equals(""))
            return null;
        
        String ambientes = ambientesTextField.getText();
        if(ambientes.equals(""))
            return null;
        
        String servicos = servicosTextField.getText();
        if(servicos.equals(""))
            return null;
        
        String bwc = bwcTextField.getText();
        if(bwc.equals(""))
            return null;
        
        Cômodos comodos = new Cômodos(dormitorios, ambientes, servicos, Integer.parseInt(bwc));
        
       
        String area = areaTextField.getText();
        if(area.equals(""))
            return null;
                        
        String valor = valorTextField.getText();
        if(valor.equals(""))
            return null;       
        
        boolean seguranca;
        if(segurancaCheckBox.isSelected())
            seguranca = true;
        else
            seguranca = false;
        
        Tipo tipo;
        if(casaRadioButton.isSelected()) //se Casa estiver selecionado
            tipo = Tipo.Casa;
         else
           if(apartamentoRadioButton.isSelected())
              tipo = Tipo.Apartamento;
           else
               return null;
            
        
        Imóvel imovel = new Imóvel(endereco, comodos, Float.parseFloat(area), Float.parseFloat(valor), seguranca, tipo);
        
        return imovel;
     
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterarButton;
    private javax.swing.JLabel ambientesLabel;
    private javax.swing.JTextField ambientesTextField;
    private javax.swing.JRadioButton apartamentoRadioButton;
    private javax.swing.JTextField areaTextField;
    private javax.swing.JLabel areaToataLabel;
    private javax.swing.JLabel bairroLabel;
    private javax.swing.JTextField bairroTextField;
    private javax.swing.JLabel bwcLabel;
    private javax.swing.JTextField bwcTextField;
    private javax.swing.JRadioButton casaRadioButton;
    private javax.swing.JLabel cepLabel;
    private javax.swing.JTextField cepTextField;
    private javax.swing.JLabel cidadeLabel;
    private javax.swing.JTextField cidadeTextField;
    private javax.swing.JLabel comodosLabel;
    private javax.swing.JLabel complementoLabel;
    private javax.swing.JTextField complementoTextField;
    private javax.swing.JButton consultarButton;
    private javax.swing.JLabel dormitoriosLabel;
    private javax.swing.JTextField dormitoriosTextField;
    private javax.swing.JLabel enderecoLabel;
    private javax.swing.JComboBox estadoComboBox;
    private javax.swing.JLabel estadoLabel;
    private javax.swing.ButtonGroup grupoBotoesbuttonGroup;
    private javax.swing.JButton inserirButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton limparButton;
    private javax.swing.JLabel numeroLabel;
    private javax.swing.JTextField numeroTextField;
    private javax.swing.JButton removerButton;
    private javax.swing.JLabel ruaLabel;
    private javax.swing.JTextField ruaTextField;
    private javax.swing.JCheckBox segurancaCheckBox;
    private javax.swing.JLabel sequencialLabel;
    private javax.swing.JTextField sequencialTextField;
    private javax.swing.JLabel servicosLabel;
    private javax.swing.JTextField servicosTextField;
    private javax.swing.JLabel valorLabel;
    private javax.swing.JTextField valorTextField;
    // End of variables declaration//GEN-END:variables
}
