
package interfaces;

import controle.ControladorPesquisa;
import entidade.Imóvel;
import entidade.Negócio;
import java.util.Vector;
import javax.swing.JOptionPane;

public class JanelaPesquisa extends javax.swing.JFrame {
    
    ControladorPesquisa controlador; //fará a intermediacao com o controlador e a janela
    
    /**
     * Creates new form JanelaPesquisa
     */
    public JanelaPesquisa(ControladorPesquisa controlador) {
        this.controlador = controlador;
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aluguelRadioButton = new javax.swing.JRadioButton();
        vendaRadioButton = new javax.swing.JRadioButton();
        clienteLabel = new javax.swing.JLabel();
        clienteTextField = new javax.swing.JTextField();
        casaRadioButton = new javax.swing.JRadioButton();
        apartamentoRadioButton = new javax.swing.JRadioButton();
        valorMinLabel = new javax.swing.JLabel();
        valorMaxLabel = new javax.swing.JLabel();
        valorMinTextField = new javax.swing.JTextField();
        valorMaxTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultadosTextArea = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        pesquisarButton = new javax.swing.JButton();
        limparButton = new javax.swing.JButton();
        resultadosLabel = new javax.swing.JLabel();

        setTitle("Pesquisa de Negócios");

        aluguelRadioButton.setText("Aluguel");

        vendaRadioButton.setText("Venda");

        clienteLabel.setText("Cliente:");

        casaRadioButton.setText("Casa");

        apartamentoRadioButton.setText("Apartamento");

        valorMinLabel.setText("Valor Mínimo:");

        valorMaxLabel.setText("Valor Máximo:");

        resultadosTextArea.setColumns(20);
        resultadosTextArea.setRows(5);
        jScrollPane1.setViewportView(resultadosTextArea);

        pesquisarButton.setText("Pesquisar");
        pesquisarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisar(evt);
            }
        });

        limparButton.setText("Limpar");
        limparButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparCampos(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pesquisarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(limparButton)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesquisarButton)
                    .addComponent(limparButton))
                .addContainerGap())
        );

        resultadosLabel.setText("Resultados:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(clienteLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(clienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(valorMaxLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(valorMaxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(casaRadioButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(apartamentoRadioButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(aluguelRadioButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(vendaRadioButton))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(valorMinLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(valorMinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(resultadosLabel)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aluguelRadioButton)
                    .addComponent(vendaRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clienteLabel)
                    .addComponent(clienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(casaRadioButton)
                    .addComponent(apartamentoRadioButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valorMinLabel)
                    .addComponent(valorMinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valorMaxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valorMaxLabel))
                .addGap(18, 18, 18)
                .addComponent(resultadosLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pesquisar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisar
        // TODO add your handling code here:
        Vector<String> visoesResultado;
        Negócio.Tipo tipoNeg = null;
        Imóvel.Tipo tipoImo = null;
        String cliente = null;
        float valorMin = -1.0f;
        float valorMax = -1.0f;
        boolean filtro = false;
        
        if(aluguelRadioButton.isSelected() && !vendaRadioButton.isSelected())
           tipoNeg = Negócio.Tipo.Aluguel;
        if(!aluguelRadioButton.isSelected() && vendaRadioButton.isSelected())
           tipoNeg = Negócio.Tipo.Venda;
        
        if(!clienteTextField.getText().isEmpty())    
            cliente = clienteTextField.getText();        
        
        if(casaRadioButton.isSelected() && !apartamentoRadioButton.isSelected())
            tipoImo = Imóvel.Tipo.Casa;
        if(!casaRadioButton.isSelected() && apartamentoRadioButton.isSelected())
            tipoImo = Imóvel.Tipo.Apartamento;
        
        if(!valorMinTextField.getText().isEmpty())
            valorMin = Float.parseFloat(valorMinTextField.getText());
        if(!valorMaxTextField.getText().isEmpty())
            valorMax = Float.parseFloat(valorMaxTextField.getText());
        
        if(tipoNeg != null || tipoImo != null || cliente != null || valorMin != -1.0f || valorMax != -1.0f)
            filtro = true;
        
        visoesResultado = controlador.pesquisa(filtro, tipoNeg, cliente, tipoImo, valorMin, valorMax);
        
        if(visoesResultado != null){
            //atulaiza Text Area
            resultadosTextArea.setText("");
            for(int i = 0; i < visoesResultado.size(); i++)
                resultadosTextArea.setText(resultadosTextArea.getText()+"\n"+visoesResultado.get(i));
        }
         else
            JOptionPane.showMessageDialog(this, "Erro Na Comunicação com Banco de Dados :(", "OPS!", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_pesquisar

    private void limparCampos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparCampos
        // TODO add your handling code here:
        aluguelRadioButton.setSelected(false);
        vendaRadioButton.setSelected(false);
        clienteTextField.setText("");
        casaRadioButton.setSelected(false);
        apartamentoRadioButton.setSelected(false);
        valorMinTextField.setText("");
        valorMaxTextField.setText("");
        resultadosTextArea.setText("");
    }//GEN-LAST:event_limparCampos

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton aluguelRadioButton;
    private javax.swing.JRadioButton apartamentoRadioButton;
    private javax.swing.JRadioButton casaRadioButton;
    private javax.swing.JLabel clienteLabel;
    private javax.swing.JTextField clienteTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limparButton;
    private javax.swing.JButton pesquisarButton;
    private javax.swing.JLabel resultadosLabel;
    private javax.swing.JTextArea resultadosTextArea;
    private javax.swing.JLabel valorMaxLabel;
    private javax.swing.JTextField valorMaxTextField;
    private javax.swing.JLabel valorMinLabel;
    private javax.swing.JTextField valorMinTextField;
    private javax.swing.JRadioButton vendaRadioButton;
    // End of variables declaration//GEN-END:variables
}
