package interfaces;

import controle.ControladorCadastroNegócios;
import entidade.Cliente;
import entidade.Imóvel;
import entidade.Negócio;
import entidade.Negócio.Tipo;
import entidade.Visão;
import java.util.Objects;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class JanelaCadastroNegócios extends javax.swing.JFrame {

    ControladorCadastroNegócios controlador; //fará a intermediacao com o controlador e a janela
    DefaultListModel listaNegocios;
    Vector <Visão<String>> visaoClientesCadastrados;
    Vector <Visão<Integer>> visaoImoveisCadastrados;
    
    /**
     * Creates new form JanelaCadastroNegócios
     */
    public JanelaCadastroNegócios(ControladorCadastroNegócios controlador) {
        this.controlador = controlador;
        visaoClientesCadastrados = Cliente.getVisões(); //o comboBox esta com o model associado a esse vetor, pega visao dos clientes cadastrados no BD       
        visaoImoveisCadastrados = Imóvel.getVisões();
        initComponents();
        inicializaLista();
    }
    
    private void inicializaLista(){
        listaNegocios = (DefaultListModel)negociosList.getModel();
        for(Visão<Integer> visão : Negócio.getVisões()){
            listaNegocios.addElement(visão);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipobuttonGroup = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        negociosList = new javax.swing.JList();
        clientesComboBox = new javax.swing.JComboBox();
        imoveisComboBox = new javax.swing.JComboBox();
        aluguelRadioButton = new javax.swing.JRadioButton();
        vendaRadioButton = new javax.swing.JRadioButton();
        fiadorCheckBox = new javax.swing.JCheckBox();
        negocioLabel = new javax.swing.JLabel();
        clienteLabel = new javax.swing.JLabel();
        imovelLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        inserirButton = new javax.swing.JButton();
        alterarButton = new javax.swing.JButton();
        removerButton = new javax.swing.JButton();
        consultarButton = new javax.swing.JButton();
        limparButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Cadastro de Negócios");

        negociosList.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(negociosList);

        clientesComboBox.setModel(new DefaultComboBoxModel(visaoClientesCadastrados));

        imoveisComboBox.setModel(new DefaultComboBoxModel(visaoImoveisCadastrados));

        tipobuttonGroup.add(aluguelRadioButton);
        aluguelRadioButton.setText("Aluguel");

        tipobuttonGroup.add(vendaRadioButton);
        vendaRadioButton.setText("Venda");

        fiadorCheckBox.setText("Fiador");

        negocioLabel.setText("Negócios:");

        clienteLabel.setText("Clientes:");

        imovelLabel.setText("Imóveis:");

        inserirButton.setText("Inserir");
        inserirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirNegocio(evt);
            }
        });

        alterarButton.setText("Alterar");
        alterarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarNegocio(evt);
            }
        });

        removerButton.setText("Remover");
        removerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerNegocio(evt);
            }
        });

        consultarButton.setText("Consultar");
        consultarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarNegocio(evt);
            }
        });

        limparButton.setText("Limpar");
        limparButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparCampos(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(inserirButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alterarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removerButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(consultarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(limparButton)
                .addGap(0, 9, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inserirButton)
                    .addComponent(alterarButton)
                    .addComponent(removerButton)
                    .addComponent(consultarButton)
                    .addComponent(limparButton))
                .addContainerGap())
        );

        jLabel1.setText("ID - (Imóvel) Negócio à: (Cliente)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aluguelRadioButton)
                    .addComponent(vendaRadioButton))
                .addGap(93, 93, 93)
                .addComponent(fiadorCheckBox)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(negocioLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(clienteLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(imovelLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(clientesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(imoveisComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(negocioLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clienteLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imoveisComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imovelLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aluguelRadioButton)
                    .addComponent(fiadorCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vendaRadioButton)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void inserirNegocio(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirNegocio
        Negócio negocio = obtemDados();
        String mensagem_erro;
        
        if(negocio != null)
            mensagem_erro = controlador.inserirNegocio(negocio);
        else
            mensagem_erro = "Algum Campo Obrigatório Não Foi Preenchido!!";
        
        if(mensagem_erro == null){
            //Adiciona sequencial de Negocio
            int sequencial = Negócio.obtemSequencial();
            negocio.setSequencial(sequencial);
            
            //se deu tdo certo adicionar negocio ao List  
            Visão <Integer> visão = negocio.getVisao(); //extrai visao na entidade
            listaNegocios.addElement(visão);
        }
         else
             JOptionPane.showMessageDialog(this, mensagem_erro, "OPS!", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_inserirNegocio

    private void alterarNegocio(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarNegocio
        Negócio negocioNovo = obtemDados();
        Negócio negocioAntigo = null;
        String mensagem_erro;
        int seqNeg = 0;
        
        Visão<Integer> visaoSelecionada = (Visão<Integer>) negociosList.getSelectedValue();
       
        if(visaoSelecionada != null){
            seqNeg = visaoSelecionada.getChave();
            negocioAntigo = Negócio.buscarNegocio2(seqNeg);
            
            negocioNovo.setCliente(negocioAntigo.getCliente());
            negocioNovo.setImovel(negocioAntigo.getImovel());
            negocioNovo.setSequencial(seqNeg);
        }
         else
            mensagem_erro = "Negócio Não Encontrado";
        
        if(negocioNovo != null)
            mensagem_erro = controlador.alterarNegocio(negocioNovo);
        else
            mensagem_erro = "Algum Campo Obrigatório Não Foi Preenchido!!";
        
        if(mensagem_erro == null){
            //atualiza list
            Visão<Integer> visaoAtual = negocioNovo.getVisao();
            for(int i = 0; i < listaNegocios.size(); i++)
                if(Objects.equals(((Visão <Integer>)listaNegocios.getElementAt(i)).getChave(), seqNeg)){
                    listaNegocios.remove(i);
                    listaNegocios.add(i, visaoAtual);
                    break;
                }
        }
         else
              JOptionPane.showMessageDialog(this, mensagem_erro, "OPS!", JOptionPane.ERROR_MESSAGE); 
    }//GEN-LAST:event_alterarNegocio

    private void removerNegocio(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerNegocio
        Visão<Integer> visaoSelecionada = (Visão<Integer>) negociosList.getSelectedValue();
        Negócio negocio = null;
        String mensagem_erro = null;
        
        if(visaoSelecionada != null)
            mensagem_erro = controlador.removerNegocio(visaoSelecionada.getChave());
        else
            mensagem_erro = "Nenhum Negócio Foi Selecionado";
        
        if(mensagem_erro == null)
            listaNegocios.removeElement(visaoSelecionada);
        else
             JOptionPane.showMessageDialog(this, mensagem_erro, "OPS!",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_removerNegocio

    private void consultarNegocio(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarNegocio
        Visão<Integer> visaoSelecionada = (Visão<Integer>) negociosList.getSelectedValue();
        Negócio negocio = null;
        String mensagem_erro = null;
        
        if(visaoSelecionada != null)
            negocio = Negócio.buscarNegocio2(visaoSelecionada.getChave());
        else
            mensagem_erro = "Nenhum Negócio Foi Selecionado";
        
        if(mensagem_erro == null){
            //setar campos....
            Visão<String> visaoCliente = negocio.getCliente().getVisao();                   
            for(int i = 0; i < visaoClientesCadastrados.size(); i++)
                  if((visaoCliente+"").equals(visaoClientesCadastrados.get(i)+"")){
                      clientesComboBox.setSelectedIndex(i);
                      break;
                  }
            
            Visão<Integer> visaoImovel = negocio.getImovel().getVisao();
            for(int i = 0; i < visaoImoveisCadastrados.size(); i++)
                  if((visaoImovel+"").equals(visaoImoveisCadastrados.get(i)+"")){
                      imoveisComboBox.setSelectedIndex(i);
                      break;
                  }

            if(negocio.getTipo() == Tipo.Aluguel)
                aluguelRadioButton.setSelected(true);
            else
                vendaRadioButton.setSelected(true);
            
            if(negocio.isFiador())
                fiadorCheckBox.setSelected(true);
            else
                fiadorCheckBox.setSelected(false);
        }
         else
            JOptionPane.showMessageDialog(this, mensagem_erro, "OPS!",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_consultarNegocio

    private void LimparCampos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparCampos
        negociosList.clearSelection();
        tipobuttonGroup.clearSelection();
        fiadorCheckBox.setSelected(false);
    }//GEN-LAST:event_LimparCampos

    private Negócio obtemDados(){
       Cliente cliente;
       Imóvel imovel;
       Visão<String> visaoCliente;
       Visão<Integer> visaoImovel;
       
       if(clientesComboBox.getSelectedItem() != null){
            visaoCliente =  (Visão<String>)clientesComboBox.getSelectedItem();
            String seqCliente = visaoCliente.getChave(); //sequencial do cliente é o Cpf
            cliente = Cliente.buscarCliente(seqCliente);
       }
        else
           return null;
          
       if(imoveisComboBox.getSelectedItem() != null){
            visaoImovel = (Visão<Integer>)imoveisComboBox.getSelectedItem();
            int seqImovel = visaoImovel.getChave();
            imovel = Imóvel.buscarImovel2(seqImovel);
       }
        else
           return null;
       
       Tipo tipo;
       if(aluguelRadioButton.isSelected())
           tipo = Tipo.Aluguel;
       else
           if(vendaRadioButton.isSelected())
               tipo = Tipo.Venda;
            else
               return null;
       
       boolean fiador;
       if(fiadorCheckBox.isSelected())
           fiador = true;
       else
           fiador = false;
       
      Negócio negocio = new Negócio(cliente, imovel, tipo, fiador); 
      
      return negocio;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterarButton;
    private javax.swing.JRadioButton aluguelRadioButton;
    private javax.swing.JLabel clienteLabel;
    private javax.swing.JComboBox clientesComboBox;
    private javax.swing.JButton consultarButton;
    private javax.swing.JCheckBox fiadorCheckBox;
    private javax.swing.JComboBox imoveisComboBox;
    private javax.swing.JLabel imovelLabel;
    private javax.swing.JButton inserirButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limparButton;
    private javax.swing.JLabel negocioLabel;
    private javax.swing.JList negociosList;
    private javax.swing.JButton removerButton;
    private javax.swing.ButtonGroup tipobuttonGroup;
    private javax.swing.JRadioButton vendaRadioButton;
    // End of variables declaration//GEN-END:variables
}
